sudo: enabled
services:
- docker
language: node_js
node_js:
- '12'
before_install:
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl
  && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
- curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
  && chmod +x skaffold && sudo mv skaffold /usr/local/bin/
install:
- yarn --cwd ./app install
script:
- yarn --cwd ./app test
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- pwd
- mkdir ${HOME}/.kube
- cp ./k8s/config.yaml ${HOME}/.kube/config
- cat ${HOME}/.kube/config
- cd ${HOME}/.kube
- sed -i 's/KUBE_CLUSTER_NAME/'"$KUBE_CLUSTER_NAME"'/g' config
- sed -i 's/KUBE_CLUSTER_CERTIFICATE/'"$KUBE_CLUSTER_CERTIFICATE"'/g' config
- sed -i 's/KUBE_CLUSTER_SERVER/'"$KUBE_CLUSTER_SERVER"'/g' config
# - sed -i 's/KUBE_CLIENT_KEY/'"$KUBE_CLIENT_KEY"'/g' config
- cat ./config   #Warn: remove it later
- sed -i 's/KUBE_ADMIN_PWD/'"$KUBE_ADMIN_PWD"'/g' config
- kubectl version
- kubectl config use-context $KUBE_CLUSTER_NAME
- cd ${TRAVIS_BUILD_DIR}
- skaffold run
env:
  global:
  - secure: 3HTlxoFWpz1OeJYH3+O/tnu+Uz+vrim+6bZdFM8w/FqaHQRFkCoV24cNGh0YXzSnrnOYplrCdXyt21bVcOHvn3YzZBauaANDzd5diK/ZbrZ0bckZnMu+NtEwAqrSdDQ9XUQ5kKjVcwAB/TdNFowejBcNwElQpJIHB6o8Qp9dF87t7cUVHmWniqE8+8tJQsn/+FA2DuZEbbOqBzWJIZUUc4DerU9DRUXG+H70Op3yt+HLy8Z1GDr8ey2l3zcf/73fH6DVjLjZ7N1Y4vCZu0b0Jp4+Xm6X6tk/wy1VCxf+J1LNEbzBH4Im+vL34TNSoDCIXFqseXP7SUkyfDDdwgG+STGUBaHfRJ3rdgXEEm0Psr7GZsNsIo24WFLDWqqnPyfYwI71FB7OG+wBtfK5Jnev7t8FdLx6WE2b7kg/D93L7iIvl+a27gLixGwaS6+YqJm3Cm74YAgnz7AyheY+KnebArPXPABrasrQwmJ/yPO+WBrK4kCBdpwLAoAS/4FlmMBDXDimRXDpBTjnLKYmHDBkzlsq+fn8QWYkSAC6tnC4aYeJxMkfsgC2TLrGyavgxgVVOFEuEY6zlR9iCaiqUbjjLitwyU73w/q6KY6AP0kH0qBvTqFRGN0cTE9RbRO1281+XwOWz6C4GduUnXNAAoDVPCI0h6cjflQlO2tUhYYCoE8=
  - secure: 16F3ZKIs/XxTZ6PY5LPbAzPlaIndW/2kD79ta9U7vNbvdH2lwYxrI9/95qqKzCJufstsqWYpPaM/6RvBWbH2VlAQIFS7UZHB8DRqx2kwkjPronJjG9OiqY0NE7eO2+JbBXdsWl/Yxknmcz5JmdK/NeZ8DtovGz2cKB3WdAUdPyDKw6nJOuLi41TVYjXUUhsBqByjE94ePUnkrWYkD+41AxpQGfkGz9VNp7KfudtoJVHpYfWTLbmWWjE3djyzp1wAcmCzeTaL8jBbbdyflANzrq3nQ6+y+H9qkrV0XPXyxqFEAjb8+/AiSfxhuNmFNlYgjE1F628iduKBqcUhqomInzdp/aQSnM8mfG1a1ZUfb8zn3ejMM2J4QnQaVnwXwf3hzaLthxTS3CGg/tEgIzIfNLz4DhsXa0O1Xl1OqkFUP9J7LM2CvcpEhjGXoIeP3pmvy/RF+BG6Vt0S0+UwDhZYZTH9bnkXucL2OLJCxg77qo6dty51+8thcT6Og+YWZrEH3oJ3wBtMPYBcQB8lXv2d/T9GhJ8O1J4oqDLR1T0ujTQafevDQdOz5A0HYfuL5ABhJnNAO40O6PlksyyBEKt5W0EwKWX362Xp7Y3BM6rWUumvPZ69Piw156WTX0UWZUNCkoWjFiPfY5mmc81sSqFXZFwwUagnXoKLN2mveAZTCR0=
