apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: testci
build:
  local:
      push: true
      useDockerCLI: true
  artifacts:
  - image: docker.io/hiram1994/test-ci
    context: app
deploy:
  kubectl:
    manifests:
    - k8s/k8s-*
