apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: KUBE_CLUSTER_CERTIFICATE
    server: KUBE_CLUSTER_SERVER
  name: KUBE_CLUSTER_NAME
contexts:
- context:
    cluster: KUBE_CLUSTER_NAME
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    username: admin
    password: KUBE_ADMIN_PWD